### ISSUE TITLE
Error while trying to load Installer.cls during docker-compose

### ISSUE THREAD

**Issue by psteiwer** [evshvarov/seabattle#3]
I get an error when I try and run `docker-compose up -d`

Here is how the environment is created:
Node: fe4f87c8e28b, Instance: IRIS

 

USER>!pwd
/usr/irissys/mgr/user

 

USER>!ls
IRIS.DAT  iris.lck  stream

 

USER>!ls /tmp/
deps  isctmperr13334

 

USER>!ls /tmp/deps
zpm.xml

 

USER>!ls /opt/seabattle
Installer.cls  src
 
 
I am getting an error at "do $SYSTEM.OBJ.Load("Installer.cls", "ck")" since this is looking in /usr/irissys/mgr/user for Installer.cls but it lives in /opt/seabattle

**Comment by evshvarov** [comment]
Are you sure you checked out the latest master?
There is
do ##class(%SYSTEM.Process).CurrentDirectory("$PWD")
in /irissession.sh which does the trick with current directory.


What is the error you are getting?

**Comment by evshvarov** [comment]
and you need to rebuild container with --no-cache
docker-compouse builld --no-cache
to let it use new stuff from the repo

**Comment by psteiwer** [comment]
Step 18/21 : RUN   do $SYSTEM.OBJ.Load("Installer.cls", "ck")   set sc = ##class(App.Installer).setup()   Do $system.OBJ.Load("/tmp/deps/zpm.xml", "ck")   zn "IRISAPP"   zpm "install webterminal"
 ---> Running in 476662a73508
standard_init_linux.go:211: exec user process caused "no such file or directory"
ERROR: Service 'iris' failed to build: The command '/irissession.sh do $SYSTEM.OBJ.Load("Installer.cls", "ck")   set sc = ##class(App.Installer).setup()   Do $system.OBJ.Load("/tmp/deps/zpm.xml", "ck")   zn "IRISAPP"   zpm "install webterminal"' returned a non-zero code: 1

**Comment by evshvarov** [comment]
@psteiwer , I think all fixed now
